#!/usr/bin/env python3
"""Pack existing Uncanny Eyes artwork for three styles in SAMD21 internal flash."""
import gzip
import json
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read_eye(path):
    text = gzip.decompress(path.read_bytes()).decode() if path.suffix == '.gz' else path.read_text()
    defines = {k: int(v) for k, v in re.findall(r'^#define\s+(\w+)\s+(\d+)', text, re.M)}
    arrays = {}
    for typ, name, body in re.findall(r'const\s+(uint\d+_t)\s+(\w+)\s*\[[^=]+?=\s*\{(.*?)\};', text, re.S):
        # The first eyelid pair is the symmetrical version used on HalloWing.
        if name not in arrays:
            arrays[name] = [int(v, 0) for v in re.findall(r'0[xX][0-9a-fA-F]+|\b\d+\b', body)]
    return defines, arrays


def resize(values, width, height, out_width, out_height):
    # Center-sampled nearest-neighbor lookup preserves source RGB565 colors and
    # packed pupil coordinates. Iris angle/distance values are already normalized.
    return [values[min(height - 1, (2*y+1)*height//(2*out_height))*width +
                   min(width - 1, (2*x+1)*width//(2*out_width))]
            for y in range(out_height) for x in range(out_width)]


def pack_rows(values, width, word_bytes):
    output = bytearray()
    offsets = []
    def emit(value):
        output.extend(value.to_bytes(word_bytes, 'little'))
    for start in range(0, len(values), width):
        offsets.append(len(output))
        row = values[start:start+width]
        i = 0
        minimum_run = 3 if word_bytes == 1 else 2
        while i < len(row):
            end = i + 1
            while end < len(row) and row[end] == row[i] and end-i < 128:
                end += 1
            if end-i >= minimum_run:
                output.append(0x80 | (end-i-1))
                emit(row[i])
                i = end
            else:
                first = i
                i += 1
                while i < len(row) and i-first < 128:
                    if i+minimum_run <= len(row) and len(set(row[i:i+minimum_run])) == 1:
                        break
                    i += 1
                output.append(i-first-1)
                for value in row[first:i]:
                    emit(value)
    offsets.append(len(output))
    assert len(output) < 65536, 'Row offsets must fit uint16_t'
    return output, offsets


def source_assets():
    human_def, human = read_eye(ROOT/'firmware/uncannyEyes/graphics/defaultEye.h')
    result = {
        'human_sclera': (human['sclera'], 200, 200, 2, True),
        'upper_lid': (human['upper'], 128, 128, 1, True),
        'lower_lid': (human['lower'], 128, 128, 1, True),
        'human_iris': (human['iris'], 256, 64, 2, False),
        'human_polar': (human['polar'], 80, 80, 2, True),
    }
    for style, name in [('lizard', 'dragonEye'), ('goat', 'goatEye')]:
        defines, arrays = read_eye(ROOT/f'assets/upstream/{name}.h.gz')
        assert arrays['upper'] == human['upper'] and arrays['lower'] == human['lower']
        result[style+'_iris'] = (resize(arrays['iris'], defines['IRIS_MAP_WIDTH'], defines['IRIS_MAP_HEIGHT'], 256, 32), 256, 32, 2, False)
        result[style+'_polar'] = (resize(arrays['polar'], defines['IRIS_WIDTH'], defines['IRIS_HEIGHT'], 128, 128), 128, 128, 2, True)
    return result


def c_array(name, values, typ):
    result = [f'static const {typ} {name}[] = {{']
    step = 16 if typ == 'uint8_t' else 12
    digits = 2 if typ == 'uint8_t' else 4
    for i in range(0, len(values), step):
        result.append('  ' + ','.join(f'0x{v:0{digits}x}' for v in values[i:i+step]) + ',')
    return '\n'.join(result) + '\n};\n'


def main():
    sections = ['// Generated by tools/build_assets.py; see THIRD_PARTY.md.\n#pragma once\n']
    report = {}
    for name, (values, width, height, word_bytes, packed) in source_assets().items():
        if packed:
            data, offsets = pack_rows(values, width, word_bytes)
            sections.append(c_array(name+'_data', data, 'uint8_t'))
            sections.append(c_array(name+'_offsets', offsets, 'uint16_t'))
            sections.append(f'static const PackedRows {name} = {{{name}_data, {name}_offsets, {width}, {height}, {word_bytes}}};\n')
            size = len(data) + 2*len(offsets)
        else:
            sections.append(c_array(name, values, 'uint16_t'))
            size = len(values)*2
        report[name] = {'raw_bytes': len(values)*word_bytes, 'stored_bytes': size, 'width': width, 'height': height}
    (ROOT/'firmware/uncannyEyes/graphics/eye_assets.h').write_text('\n'.join(sections))
    (ROOT/'assets/memory.json').write_text(json.dumps(report, indent=2)+'\n')
    print(json.dumps(report, indent=2))
    print('Total artwork bytes:', sum(item['stored_bytes'] for item in report.values()))


if __name__ == '__main__':
    main()
